# Generated by Django 3.0.4 on 2020-03-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('base', '0005_personindexpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonIndexPage',
        ),
    ]
